# Generated by Django 4.2.17 on 2025-01-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=100, null=True)),
                ('branch_image', models.ImageField(blank=True, null=True, upload_to='branches/')),
            ],
        ),
    ]
