# Generated by Django 4.2.17 on 2025-01-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=100, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='branch',
        ),
    ]
