# Generated by Django 4.2.17 on 2025-01-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gallery_delete_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branch_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
