# Generated by Django 4.2.17 on 2025-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_branches_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branch_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
