# Generated by Django 4.2.17 on 2025-02-07 08:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_promo_delete_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='careermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('Last_name', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NONE', 'Prefer not to say')], default='NONE', max_length=20)),
                ('phone_no', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('current_location', django_countries.fields.CountryField(max_length=2)),
                ('dob', models.DateField()),
                ('attach_cv', models.FileField(upload_to='attachment_cv')),
                ('status', models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion/'),
        ),
    ]
