# Generated by Django 4.2.17 on 2025-02-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_careermodel_attach_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careermodel',
            name='dob',
        ),
        migrations.AddField(
            model_name='careermodel',
            name='age',
            field=models.IntegerField(default='21'),
        ),
    ]
