# Generated by Django 4.2.17 on 2025-02-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_careermodel_dob_careermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermodel',
            name='age',
            field=models.IntegerField(default=''),
        ),
    ]
