# Generated by Django 4.2.17 on 2025-02-07 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_careermodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_event_name', models.CharField(default='', max_length=100)),
                ('blog_description', models.CharField(default='', max_length=1000, null=True)),
                ('blog_event_image', models.ImageField(blank=True, null=True, upload_to='Blogs/')),
                ('posted_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
